.jupyter/jupyterhub_config.py, jupyterhub-singleuser-profile.cm.yaml
Also use merged profile rather than just first returned
=> Remove environment variable config in favour of singleuser_profiles, add properties for mem_limit

.jupyter/jupyterhub_config.py, requirements.txt
Moved to singleuser profiles. Related to PR: https://github.com/vpavlin/jupyterhub-singleuser-profiles/pull/17
=> Moved image list implementation

requirements.txt
This brings in multiple new features:
1. New style of deploying services for users (e.g. spark)
2. Images are loaded by labels, not imagestream names
3. Resources are defined as in Kubernetes, not a custom format
4. Env vars are defined as in kubernetes
=>  Update JupyterHub Singleuser Profiles

.jupyter/jupyterhub_config.py, requirements.txt
To verify the PR check that:
* GPU request is set when GPU set to >0
* Profile resource configuration is applied properly when Size "Default" is selected
=> Update SingleuserProfiles initialization to match new version

requirements.txt
=> Update JupyterHub Singleuser Profiles to point to a new organization

.aicoe-ci.yaml
…
CI is failing with the non-existing image
=> Fix the base image

.aicoe-ci.yaml, .jupyter/jupyterhub_config.py, requirements.txt
Fixing authentication issues with the latest changes to jupyterhub-quickstarts repository
=> Update dependencies and jupyterhub config to work with the new upstream repo

.aicoe-ci.yaml
…
Fixing the base image version name
=> Fix base image version

.jupyter/jupyterhub_config.py, .s2i/bin/assemble, Pipfile, Pipfile.lock
Added parts of code necessary to run the JSP-API service necessary to run the new Spawner UI.
Also modified the interaction with the UI itself.
Related to: opendatahub-io/jupyterhub-singleuser-profiles#41
=> Reworked spawner

Pipfile, Pipfile.lock
=> Updated JSP to 0.1.0

.aicoe-ci.yaml
…
This PR updates base image for the CI build
=> Update base image to v3.5.2

.jupyter/jupyterhub_config.py, Pipfile, Pipfile.lock
https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/issues/80
=> Added default mount path variable

.jupyter/jupyterhub_config.py
see https://github.com/opendatahub-io/odh-manifests/pull/330
=> service account for prometheus /metrics endpoint

Pipfile, Pipfile.lock
=> Update JSP to 0.1.2

.aicoe-ci.yaml
Fixes: https://github.com/opendatahub-io/odh-manifests/issues/311
Update the base image to pick up changes which enable upgrading database on pod start
=> Update the base image to pick up the upgrade-db change

.jupyter/jupyterhub_config.py, Pipfile, Pipfile.lock
~*NOTE:* `Pipefile` and `Pipfile.lock` needs to be fixed! This is just for testing!~
… Explain your changes.
=> Update the JH config for latest JSP

Pipfile, Pipfile.lock
Spawner UI missed IDs in DOM for Env vars. This update fixes it
… Explain your changes.
=> Update JSP to 0.2.2

Pipfile, Pipfile.lock
…
This PR fixes a bug where when a size was selected, GPU selection got overwritten for the user
=> Update JSP to 0.2.3

Pipfile, Pipfile.lock
ODH CI is hittin a bug where Selenium is too fast and JSP UI rewrites the image selection. This update fixes it
… Explain your changes.
=> Update JSP to 0.2.4 to fix CI bug

Pipfile, Pipfile.lock
See the changelog here: https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/pull/127
Update to JupyterHub Singleuser Profiles
=> Update JSP to 0.3.0

.jupyter/jupyterhub_config.py, .s2i/bin/assemble, Pipfile, Pipfile.lock
…
… Explain your changes.
This PR updates JupyterHub Singleuser Profiles to 0.4.0 - see changelog: https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/pull/143
=> Update JSP to 0.4.1

.jupyter/jupyterhub_config.py, Pipfile, Pipfile.lock
=> Add JUPYTERHUB_LOGIN_URL to JSP service

Pipfile, Pipfile.lock
=> Update JSP to 0.5.1

.jupyter/jupyterhub_config.py, Pipfile, Pipfile.lock
https://issues.redhat.com/browse/ODH-421
…
This Pull request installs the jupyterhub-traefik-proxy which will be used to write the routes to a .toml file in a configmap and connect to the external Traefik proxy.
=> Add traefik dependancy

readinessProbe.sh
https://issues.redhat.com/browse/ODH-453
Adds a new file, which can act as an livenessProbe script
Add an script that works as a liveness probe for jupyterhub on odh.
=> Added readiness probe script

.jupyter/jupyterhub_config.py, Pipfile, Pipfile.lock
=> Update JSP to 0.6.3

.jupyter/jupyterhub_config.py
…
Changes the behavior of image gathering to fix image pull back error during spawn when using the new modal spawn information window.
=> Get image directly during pre-spawn, instead of using form.

.jupyter/jupyterhub_config.py, Pipfile, Pipfile.lock
…
This PR fixes a bug related to using custom namespaces with the new bugfix introduced in PR #123 
Testing instructions:
1. Deploy the modifed jupyterhub-odh image
2. Attempt spawning notebook in a custom namespace
=> Modify image gathering for custom namespaces

.thoth.yaml
Signed-off-by: Landon LaSmith <LLaSmith@redhat.com>
N/A
Update the maintainers list in the Thoth files
N/A
=> Update thoth maintainers list
